"""add single_parent

Revision ID: 196e86b361cd
Revises: de11943b5006
Create Date: 2025-09-28 10:27:33.859309

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "196e86b361cd"
down_revision: Union[str, Sequence[str], None] = "de11943b5006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
