"""add title to Resume model

Revision ID: de11943b5006
Revises: b048df433648
Create Date: 2025-09-27 21:41:33.380291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de11943b5006"
down_revision: Union[str, Sequence[str], None] = "b048df433648"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resumes", sa.Column("title", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "title")
    # ### end Alembic commands ###
