"""update cascade logic

Revision ID: 21086b7df9c1
Revises: 196e86b361cd
Create Date: 2025-10-12 08:57:54.089044

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "21086b7df9c1"
down_revision: Union[str, Sequence[str], None] = "196e86b361cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("resumes_user_id_fkey"), "resumes", type_="foreignkey")
    op.create_foreign_key(
        None, "resumes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resumes", type_="foreignkey")
    op.create_foreign_key(
        op.f("resumes_user_id_fkey"), "resumes", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
